export const donationSponsorshipContent = {
  hero: {
    eyebrow: 'Give Help',
    title: 'Help children move forward with practical support, trusted giving, and clear sponsorship pathways.',
    copy:
      'You can support the Trust as an individual donor, a monthly supporter, or a corporate sponsor. We keep unverified details clearly marked as TBD_VERIFIED until the Trust confirms them.',
    primaryCta: 'Support the Mission',
    secondaryCta: 'Become a Sponsor',
    tertiaryCta: 'Request Sponsorship Information',
  },
  pathways: [
    { label: 'Make a once-off donation', href: '#individual-giving' },
    { label: 'Become a monthly supporter', href: '#individual-giving' },
    { label: 'Sponsor as a company', href: '#corporate-sponsorship' },
    { label: 'Donate goods or services', href: '#ways-to-support' },
    { label: 'Request verification before giving', href: '#verification' },
    { label: 'Speak to the team', href: '#enquiry-form' },
  ],
  trust: {
    title: 'Before you give, we want you to feel confident.',
    copy:
      'Mpho Madi Trust Fund welcomes donors and sponsors who want to understand the work, verify details, and support responsibly.',
    benefits: [
      'Organisation purpose and support focus',
      'Who benefits from the work',
      'How funds are used',
      'Verification note for unresolved details',
      'Contact option for legitimacy checks',
    ],
    checklist: [
      'Confirm banking details',
      'Confirm organisation details',
      'Ask for programme information',
      'Request sponsorship proposal if donating as a company',
      'Keep proof of payment',
    ],
    verification: [
      'Registration / compliance details: TBD_VERIFIED',
      'Banking details: TBD_VERIFIED',
      'Board / leadership details: TBD_VERIFIED',
      'Support documents: request from the team',
    ],
  },
  donationAmounts: [
    { amount: 'R100', impact: 'Can contribute toward essential support items, depending on current programme needs.', cta: 'Choose R100' },
    { amount: 'R250', impact: 'Can contribute toward essential support items, depending on current programme needs.', cta: 'Choose R250' },
    { amount: 'R500', impact: 'Can contribute toward practical help such as food, clothing, transport, or follow-up support.', cta: 'Choose R500' },
    { amount: 'R1,000', impact: 'Can contribute toward a larger support step, subject to what the Trust needs most right now.', cta: 'Choose R1,000' },
    { amount: 'Custom', impact: 'Choose a custom amount that fits your giving capacity and preferred support pattern.', cta: 'Choose custom' },
  ],
  givingOptions: [
    {
      title: 'Once-off donation',
      amount: 'Any amount',
      copy: 'Make a single contribution that supports urgent needs, practical follow-up, and active family cases.',
      cta: 'Donate once',
    },
    {
      title: 'Monthly supporter',
      amount: 'From your chosen amount',
      copy: 'Become a steady supporter and help the Trust plan support with more confidence across the year.',
      cta: 'Become monthly',
    },
    {
      title: 'In-kind donation',
      amount: 'Goods or services',
      copy: 'Donate groceries, clothes, stationery, equipment, or professional services that reduce pressure on the Trust.',
      cta: 'Offer in-kind support',
    },
    {
      title: 'Volunteer / professional support',
      amount: 'Skills-based support',
      copy: 'Offer volunteer help or professional expertise if you want to contribute time or specialised services.',
      cta: 'Offer your skills',
    },
  ],
  sponsorBenefits: [
    'CSI / CSR alignment',
    'Community impact story',
    'Brand visibility opportunities',
    'Programme support options',
    'A clear contact path for meetings',
  ],
  sponsorTiers: [
    {
      title: 'Bronze Sponsor',
      fit: 'Good for smaller companies or first-time partners',
      focus: 'Visible community support with a simple entry point',
      recognition: 'Recognition can be added once approved',
    },
    {
      title: 'Silver Sponsor',
      fit: 'Good for growing businesses looking for CSI / CSR alignment',
      focus: 'A stronger partnership with more visible support',
      recognition: 'Recognition can be added once approved',
    },
    {
      title: 'Gold Sponsor',
      fit: 'Good for established partners wanting broader visibility',
      focus: 'Greater partnership depth and community impact',
      recognition: 'Recognition can be added once approved',
    },
    {
      title: 'Programme Sponsor',
      fit: 'Good for companies backing a named programme',
      focus: 'School supplies, food support, clothing, or community programmes',
      recognition: 'Recognition can be added once approved',
    },
    {
      title: 'Strategic Partner',
      fit: 'Good for long-term collaborators and anchor partners',
      focus: 'Deeper relationship, planning, and support visibility',
      recognition: 'Recognition can be added once approved',
    },
  ],
  supportWays: [
    'EFT donation',
    'Sponsor a programme',
    'In-kind donation',
    'Monthly giving',
    'Corporate partnership',
    'Volunteer / professional services',
    'Share the cause',
  ],
  ctas: {
    support: 'Support the Mission',
    sponsor: 'Become a Sponsor',
    requestSponsorInfo: 'Request Sponsorship Information',
    requestVerification: 'Request verification documents',
    speakToTeam: 'Speak to the team',
    submitEnquiry: 'Submit enquiry',
    downloadProposal: 'Download Sponsorship Proposal',
  },
  sponsorProposal: {
    available: false,
    href: '/documents/mpho-madi-sponsorship-proposal.pdf',
    label: 'Sponsorship proposal document: TBD_VERIFIED / Coming soon',
  },
  faq: [
    {
      q: 'How do I donate?',
      a: 'Use the support buttons on this page, then contact the team for the verified donation method or next step.',
    },
    {
      q: 'Can my company sponsor a programme?',
      a: 'Yes. Use the sponsor section to request information or arrange a meeting about programme support.',
    },
    {
      q: 'Can I donate goods instead of money?',
      a: 'Yes. In-kind support such as groceries, clothing, stationery, equipment, or services can be requested.',
    },
    {
      q: 'Can I request verification documents?',
      a: 'Yes. The page keeps unverified items visible and gives you a direct way to request documents.',
    },
    {
      q: 'Can I become a monthly supporter?',
      a: 'Yes. Monthly support is one of the main giving paths on the page.',
    },
    {
      q: 'Will I receive feedback after supporting?',
      a: 'The Trust should follow up through the enquiry process and later admin flow once it is connected.',
    },
    {
      q: 'Can I request a meeting before committing?',
      a: 'Yes. The sponsor section includes a meeting request path.',
    },
    {
      q: 'Are banking details verified?',
      a: 'Any banking details must remain marked TBD_VERIFIED until the Trust confirms them.',
    },
  ],
  form: {
    supportTypes: [
      'Individual donor',
      'Monthly supporter',
      'Corporate sponsor',
      'In-kind donor',
      'Volunteer / professional supporter',
      'I need more information first',
    ],
    interests: [
      'Once-off donation',
      'Monthly support',
      'Sponsor tier',
      'Programme sponsorship',
      'Goods / services donation',
      'Request verification documents',
      'Request meeting',
    ],
  },
  leadShape: `donationSponsorLead = {
  id,
  leadType,
  fullName,
  email,
  phone,
  companyName,
  donationAmount,
  donationFrequency,
  sponsorTierInterest,
  supportType,
  message,
  wantsVerificationDocuments,
  wantsMeeting,
  proofOfPaymentUrl,
  status,
  assignedTo,
  internalNotes,
  createdAt,
  updatedAt
}`,
  statuses: ['new', 'contacted', 'awaiting_payment', 'awaiting_documents', 'verified', 'converted', 'closed', 'archived'],
}
